<a href="https://colab.research.google.com/github/kushagrabhadauria21/Data_Preprocessing/blob/main/Datapreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Importing Libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## **Importing Dataset**


In [2]:
df= pd.read_csv("Data.csv")
X=df.iloc[:, :-1]
y=df.iloc[:, -1]


##**Dealing with missing Data**


In [3]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(X.iloc[:,1:3])
X.iloc[:,1:3]=imp.transform(X.iloc[:,1:3])
X



Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

##**Encoding Categorical Data**


In [4]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
np.set_printoptions(suppress=True, precision=1)
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [0])], remainder="passthrough")
X = np.array(ct.fit_transform(X))
X



array([[    1. ,     0. ,     0. ,    44. , 72000. ],
       [    0. ,     0. ,     1. ,    27. , 48000. ],
       [    0. ,     1. ,     0. ,    30. , 54000. ],
       [    0. ,     0. ,     1. ,    38. , 61000. ],
       [    0. ,     1. ,     0. ,    40. , 63777.8],
       [    1. ,     0. ,     0. ,    35. , 58000. ],
       [    0. ,     0. ,     1. ,    38.8, 52000. ],
       [    1. ,     0. ,     0. ,    48. , 79000. ],
       [    0. ,     1. ,     0. ,    50. , 83000. ],
       [    1. ,     0. ,     0. ,    37. , 67000. ]])

In [5]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y=le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

##**Splitting the Dataset**

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=1)
X_test

array([[    0.,     1.,     0.,    30., 54000.],
       [    1.,     0.,     0.,    37., 67000.]])

##**Feature Extraction using Standardisation**


In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]= sc.fit_transform(X_train[:,3:])
X_test[:,3:]= sc.transform(X_test[:,3:])

In [8]:
X_train

array([[ 0. ,  0. ,  1. , -0.2, -1.1],
       [ 0. ,  1. ,  0. , -0. , -0.1],
       [ 1. ,  0. ,  0. ,  0.6,  0.6],
       [ 0. ,  0. ,  1. , -0.3, -0.3],
       [ 0. ,  0. ,  1. , -1.9, -1.4],
       [ 1. ,  0. ,  0. ,  1.1,  1.2],
       [ 0. ,  1. ,  0. ,  1.4,  1.6],
       [ 1. ,  0. ,  0. , -0.7, -0.6]])

In [9]:
X_test


array([[ 0. ,  1. ,  0. , -1.5, -0.9],
       [ 1. ,  0. ,  0. , -0.4,  0.2]])